### ISSUE TITLE
2 sliders in one website

### ISSUE THREAD

**Issue by lukpeta** [kthornbloom/Smoothslides#11]
Hi,
I have 2 sliders in one website: http://46.29.150.76/test3/index.html
and it's not working :(

Can you help me?

Northwest

**Comment by kthornbloom** [comment]
Hello, I'm sorry but it was written to only support one instance per page. It may be something I update later on, but I don't have time at the moment.

**Comment by lukpeta** [comment]
OK, thank you

**Comment by kthornbloom** [comment]
Version 2 now supports this!
