### ISSUE TITLE
Various suggestions

### ISSUE THREAD

**Issue by fhickler** [kthornbloom/Smoothslides#12]
I was tasked by a client to "add a ken burns effect" to a bootstrap carousel. I searched for many solutions and yours was the best I could find. There were more comprehensive plugins, but they seemed to all cost money and were pretty bloated compared to smoothsliders.

Few suggestions:
- The only way I could see to remove the rotation from the animation was to edit the js directly. Is there an option I missed? If not, I suggest adding one.
- A callback hook for the transition start and end would be useful. I achieved what I wanted (a caption animation) by adding code to the captionUpdate function. I tried adding a function to an external js file that listened for the transition.end event. This almost worked, but I couldn't get my custom animation to happen before the caption text had been added to the dom, causing the incoming caption to display for a split second before the caption animation. So I edited the captionUpdate function in the smoothsliders js directly.
- It would be nice if the slides would continue to animate during the transition. I achieved this half way by editing the line: "fullTime= options.effectDuration + options.transitionDuration," by removing "+ options.transitionDuration". That made the out-going animation continue through the transition, but the incoming animation would still wait for the transition to end first. 
- One nice thing was that I had wanted multiline captions, and to my surprise, the alt text respected br tags within it. You might want to document this fact.

Anyway - if my js skills were a little better, I would maybe try contributing to the project. But thanks for a useful plugin.

**Comment by kthornbloom** [comment]
Thanks for the feedback! 

- Correct, the only way to remove the rotation on zoomIn & zoomOut is in the JS. I suppose effects with rotations should maybe have a separate name. I may change that in the future.
- Smoothslides uses all CSS animations (rather than jQuery/javascript ones) which helps with performance. The downside is that CSS animations do not have callbacks. The best you can do is put your extra code within setTimeout, and have the timeout the same length as the transition.
- I'll look into it as I have time, but I think there would be some issues with having an opacity transition applied halfway through another CSS transition. 
- Glad it worked out!

**Comment by fhickler** [comment]
Apparantly there is a way to detect the end of a css transition. I learned about it today from this article:
https://jonsuh.com/blog/detect-the-end-of-css-animations-and-transitions-with-javascript/
I actually tried using this technique to trigger a function that animated the caption onto the screen. It basically worked, but the problem was that the timing of it was such that the new caption would appear on the screen for a split second, and then the animation would trigger (because smoothsliders was adding the caption the dom just before my function heard the transition end event). But if you could integrate this technique into your code in the right way, it could provide a way for custom caption animations (and other things that could be triggered on slide transition). Just a thought.

**Comment by kthornbloom** [comment]
Yeah, I actually did try detecting transitionEnd for callbacks when I started this plugin, but found that method to be pretty buggy and unreliable. Looks like that author has worked out some of the issues though.

**Comment by kthornbloom** [comment]
Closing this issue as I'm not planning on adding callback hooks at this time. As you mentioned, using the caption function is probably the easiest way to accomplish that at the moment.
