### ISSUE TITLE
IE 8 compatibility

### ISSUE THREAD

**Issue by fhickler** [kthornbloom/Smoothslides#14]
Hello again -
So, as far as I could tell, the ss demo at kthornbloom.com/smoothslides works well in IE8 (albeit without the kenburns effect), but the current distribution doesn't even seem to appear in IE8. Is the demo on your site an older version? Am I correct that the current version is incompatible with IE8? If this is correct, do you know offhand of a good way of handling a ss v2.0.0  carousel on IE8? Thanks.

**Comment by kthornbloom** [comment]
Hey, this version got updated to jQuery 2 which is IE 9+. I haven't tested,
but you should be able to run it with jQuery 1.8 to get IE8 support.

**Comment by fhickler** [comment]
I just tried a test with ss 2 and jquery 1.8.3 and again the slides didn't appear at all in ie8 (though it seemed to work fine in IE 9 and 10)

**Comment by kthornbloom** [comment]
Hi there. Please update to <a href="http://kthornbloom.github.io/Smoothslides/">version 2.1.0</a> and use jQuery 1.x. I believe it should function in IE8 now, although you'll miss out on the Ken Burns effect. (That's all done with CSS transitions which IE8 doesn't have, of course.)

**Comment by fhickler** [comment]
so far works great. Thanks!
