### ISSUE TITLE
Slides fail to display if carousel is hidden at first

### ISSUE THREAD

**Issue by fhickler** [kthornbloom/Smoothslides#15]
If the carousel is set to "display:none" when the page loads and is later changed to "display:block", the slides fail to display. I traced it to line 28 where ss is getting the maxwidth value from the image width (which, if it isn't currently displayed, is 0).

This might sound like an edge case, but one place it comes into play (where I in fact encountered it) is in a bootstrap page where the carousel, or one of it's ancestors, is given a class of hidden-xs. If you load the page at a large size and then resize the browser, it shows and hides as expected. If you load the page at an xs size and then expand the browser, the slides don't display.

I actually worked around this by changing line 28 to "maxwidth=9999" and let bootstrap set the maxwidth of the carousel's container element. So far I haven't found any side effects from this work-around.

In any case, I don't know what to suggest as a fix, so I thought I would just report it.

**Comment by kthornbloom** [comment]
I've added a 'known issues' part to the help section here http://kthornbloom.github.io/Smoothslides/  Setting that max-width to your image's width manually ought to fix the issue, I believe. Thanks for the report!

**Comment by fhickler** [comment]
Just a tiny clarification - the issue only occurs if the carousel is hidden on page load. If it is shown on page load, and then later hidden and reshown, there is no problem. In any event, thanks again - even with these issues, your plugin saved me from struggling with adding css animations and transitions to the standard bootstrap carousel.

> On Jul 2, 2015, at 7:29 AM, Kevin Thornbloom notifications@github.com wrote:
> 
> I've added a 'known issues' part to the help section here http://kthornbloom.github.io/Smoothslides/ http://kthornbloom.github.io/Smoothslides/ Setting that max-width to your image's width manually ought to fix the issue, I believe. Thanks for the report!
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/kthornbloom/Smoothslides/issues/15#issuecomment-118013803.

Fred Hickler
fred@fisheyeworld.com
