### ISSUE TITLE
pagination dots not visible

### ISSUE THREAD

**Issue by ghost** [kthornbloom/Smoothslides#16]
I used Smoothslides on a bootstrap intranet site and I am very pleased about the result. However, the pagination dots are not visible (though they exist - the mouse pointer changes and clicking on them works). The background color in by page is white and I notice that in your demo page there is a light pink background color. Do you have any idea about what should I do?  (I am not that experienced with CSS)

**Comment by kthornbloom** [comment]
Sure, you can change the color in css/smoothslides.theme.css 

Look for the line that starts like:
`.ss-paginate a:link, .ss-paginate a:visited {`
and change the value for the background.
