### ISSUE TITLE
Change fading between slides to slide left/right

### ISSUE THREAD

**Issue by designloud** [kthornbloom/Smoothslides#17]
By far the best and most lightweight script I have come across with the Ken Burns effect.  One thing I am trying to accomplish here is instead of fading between slides I would love to have the ability to have a "sliding" effect where it slides left or right to the next slide.

Peeking in your main JS file I can see where you modify the CSS for the active and inactive elements to change opacity from 0 to 1.  My question or "issue" (Although I think its more a feature request) is can these be easily modified to make slides slide across left to right?  I tried playing with the FadeOutLast Function and since I am only using the zoom in effect I tried modifying that as well but dont quite get the results I am looking for.  Can you help?

`function fadeOutLast() {
                // Crapbag (<=IE9) detector
                if (document.all && !window.atob){
                    // Crapbag detected! Use jQuery to fade
                    $('#'+uniqueId).find('.ss-slide:last').animate({
                        'left':'0'
                    })
                    console.log('1');
                } else {
                    // Fade out last with CSS
                    console.log('2');
                    $('#'+uniqueId).find('.ss-slide:last').css({
                        'transition':'all '+options.transitionDuration+'ms',
                        'left':'0'
                    });
                }
            }

that.zoomIn = function() {
                fadeOutLast();
                // Set up next
                $(this).find('.ss-slide:eq(-2)').css({
                    'transition':'none',
                    'transform':'scale(1.1) rotate(-1.5deg)'
                });
                setTimeout(function(){
                    // Wait for fade, then sort & animate next
                    $(that).find('.ss-slide:last').prependTo($(".ss-slide-stage", that)).css({
                        'right':'0',
                        'transform':'none'
                    });
                    $(that).find('.ss-slide:last').css({
                        'transition': 'all ' + options.effectDuration + 'ms ' + options.effectEasing +'',
                        'transform':'scale(1.3) rotate(0deg)'
                    });
                }, options.transitionDuration);
            }`

**Comment by kthornbloom** [comment]
Thanks for the kind words! So to slide the image out, you'd want to set the left value to 100% rather than zero like this:

```
function fadeOutLast() {
            // Crapbag (<=IE9) detector
            if (document.all && !window.atob){
                // Crapbag detected! Use jQuery to fade
                $('#'+uniqueId).find('.ss-slide:last').animate({
                    'left':'100%'
                })
            } else {
                // Fade out last with CSS
                $('#'+uniqueId).find('.ss-slide:last').css({
                    'transition':'all '+options.transitionDuration+'ms',
                    'left':'100%'
                });
            }
        }
```

... however there are two problems to consider. One is that you'll then need to set the left position back to zero once the image is hidden so it shows up the next time. That shouldn't be hard. The other is that to provide the Ken Burns effect, these images are scaled larger in many of the effects. That means that when you change the left value to 100%, there's still going to be some of the image visible because it's scaled larger than what it actually is. So you may need to play with that percent and use something larger.

**Comment by designloud** [comment]
Thanks for the quick response and again, great work.  I created a fiddle Im working on getting right for anyone wanting to do this in the future.  I will keep tinkering to see if I can get it working.  If I do I will paste the solution here for future searches. https://jsfiddle.net/Lx41omrq/2/

**Comment by kthornbloom** [comment]
Sounds good! Feel free to open a branch & pull request if you get it sorted out. I could see it being a good feature to add.
