### ISSUE TITLE
Add option for modifying the 'strength' of each effect.

### ISSUE THREAD

**Issue by mindshaped** [kthornbloom/Smoothslides#18]
EDIT- Add an option to modify how much movement each effect is using throughout the transition.

<hr>

Hey, thanks for the neat slider!

I'm trying to use it for a fluid and autoplayed slideshow with ken burns effect.

The only issue here, the option "effectDuration" seems to be identical with the autplay timeout (time until the slider automatically moves to the next slide). It would be awesome if effectDuration and timeout could be handled separately, for the following scenario:

– to be able to set a timeout for the autoplay changes (for example 3 seconds)
– set a separate effectDuration (for ex. a very high one like 20000) in order to get a really slow and unflashy effect (because when setting to 3 seconds it's really fast).

I tried by using setInterval and a click-trigger on the prev/next buttons via jQuery, though when clicking or triggering prev/next, the ken burns effect seems to stop on the following slide (also in the demo, when advancing to other images). 

thx
-N

**Comment by kthornbloom** [comment]
So is your goal to have a very subtle effect, while still changing to the next image fairly quickly?

**Comment by mindshaped** [comment]
yep exactly,

I solved it by directly modifying the unminified source (maybe that would be neater by creating an additional option) :

smoothslides-2.1.0.min.js:26 > variable fulltime set to the desired number
smoothslides-2.1.0.min.js:66 > set desired number for the timeout

**Comment by kthornbloom** [comment]
Ok, yeah I was going to suggest you just modify the values of the individual effects. I think adding an option called something like "effectModifier" would be useful though. I may work on that someday soon!

**Comment by kthornbloom** [comment]
Added in V 2.2.0
