### ISSUE TITLE
Start slideshow again after changing images

### ISSUE THREAD

**Issue by LasseKofoed** [kthornbloom/Smoothslides#20]
Hi Kevin

How to restart/reinit the slideshow again when images has been removed or added.
Calling the  $('#obj').smoothSlides(); again results in the multiple instance running.

**Comment by kthornbloom** [comment]
Unfortunately, this plugin was not written to work with dynamically added images. I would suggest removing, and then replacing the entire element and then re-calling the function if possible.

**Comment by LasseKofoed** [comment]
What is the best way to remove the element and bindings. ?

I can remove it, and add it again, but each slide are halting for a few sec. and then jumping to the where the animations should have been and continues the animation.

I have tried with the following

 $.removeData($('#environmentSlideShow').get(0));
    $('#environmentSlideShow').unbind();
    $('#environmentSlideShow').empty();
    $('#environmentSlideShow').remove();
    $(".environmentSlideShowContainer").append(" 

<div id=\"environmentSlideShow\" class=\"swiper-container-Environment top smoothslides\"></div>

"); 

Can you point me in the right direction ?
