### ISSUE TITLE
ie9?

### ISSUE THREAD

**Issue by poomato** [kthornbloom/Smoothslides#21]
Hey, love the script. Glad you added captions.

This guy managed to get Ken Burns on ie9 (even ie7), would it be possible to figure out how he did it and implement? I think it might be the Transit plugin.

http://slideshowify.com/

**Comment by kthornbloom** [comment]
Hi there,

The Slideshowify plugin looks pretty nice! Transit is actually just makes it easier to manipulate CSS animations with javascript. To achieve more browser support, Slideshowify falls back to regular jQuery frame-by-frame animations. However, he mentions not all of the animations will work correctly:

<i>"Obviously, browsers which support CSS3 transitions will produce better results. The plugin falls back to plain old frame animation for others, and zoom transitions aren't supported in this case."</i>

I don't plan to provide fallbacks in Smoothslides for a few reasons:
• jQ animations will typically have bad framerates
• Smoothslides is set up with each effect in a separate function. This allows for the potential to add new effects that may be different than the Ken Burns type. However, it would make it even harder to add fallbacks.
• The overall weight of the plugin would grow quite a bit.
