### ISSUE TITLE
start effect (zoomIn) immediately?

### ISSUE THREAD

**Issue by bananacat2015** [kthornbloom/Smoothslides#22]
Hey Kevin,

first off all thank you for this great slider!

I have got one questions: How can I make the animation-effect (e.g. zoomIn) starting immediattely? I have got   effectDuration: 9000 and transitionDuration: 2000 fpr a smooth change. But it takes a little while until the zooming gets started?

Is there a way to integrate a "time-until-start"-option?

THANKS A LOT
Rene

**Comment by kthornbloom** [comment]
Hi Rene, a long transitionDuration will unfortunately cause a delay in the slideshow getting started. A time-until-start option would be nice! I probably won't be able to implement that soon, but I'll keep in mind for future updates.

**Comment by bananacat2015** [comment]
ok thank you anyway
