### ISSUE TITLE
Vertically center the photos

### ISSUE THREAD

**Issue by DanieleDDM** [kthornbloom/Smoothslides#23]
Hi, there is a way to center the photo vertically if the container height is smaller than the images height.
Now the image is anchored on top, but I wish center it to vertically because I use SmoothSlides for the full screen slider and if I have a wider monitor the image will be cut on bottom.

Thank'you! :)

**Comment by DanieleDDM** [comment]
Solved with this code in the page:

``` javascript
<script type="text/javascript">     

        //-- Vertical center function --//
        function verticalCenter(){
            var hImg =  $('.ss-slide-stage img').height();
            var hStage =  $('.homeSlider').height();
            if(hImg>hStage){
                var pxTranslate = (hImg-hStage)/2;
                $('.ss-slide-stage .ss-slide').css('top', -pxTranslate);
            }
        }


        $(window).load(function() { 
            verticalCenter()
        })  

        //Resizing
        $(window).resize(function(){
             setTimeout(function(){
                 verticalCenter();
            },50);
        });

</script> 
```

**Comment by kthornbloom** [comment]
Hi! I'm glad you solved it. When I wrote this plugin, I did so thinking that the images would all be the same size, so that's why it doesn't handle different sized images by default.
