### ISSUE TITLE
chrome crashes with slideshow with more than 30 images

### ISSUE THREAD

**Issue by mazlmazl** [kthornbloom/Smoothslides#28]
I made a slideshow, which runs on a kiosk browser/machine in fullscreen mode.
I would like to create a slideshow, which reads out all images files from a folder with PHP.
But if there are more than about 20 images in the folder, Chrome doesn´t show the slide effects.
If there are more than 30 images, Chrome crashes.
I have exactly the same issues on an Intel Atom with 2GB and integrated GPU and on an Intel i5 with 4GB and integrated CPU.
So, I think, it does not depend on the hardware.
The images have all a size of 250kb.

Is there an easy way to load more images without issues?
If not, I guess the only other way is to change the images during the slideshow with jquery, right?

**Comment by kthornbloom** [comment]
While the amount of images does affect some things, it's probably the size of the slideshow that's a bigger deal. If it's full-screen, you are forcing the entire page to re-paint while the animations are going on. I've used this slideshow in large areas and never experienced crashes or problems, but I usually work on machines with decent specs. To answer your question, there isn't any way to optimize this slideshow any more besides using it at a smaller size.

**Comment by mazlmazl** [comment]
My solution:
I made 100 slideshows with only 15 images in each.
Now, I start one slideshow after the other and fade between them.
