### ISSUE TITLE
Loading .gif image missing at the start

### ISSUE THREAD

**Issue by maofree** [kthornbloom/Smoothslides#5]
Hi kevin
using your plugin I find something to improve, then you decide if you want to add or not
if in the gallery there are ex. 10 big images the slide container is blank for some seconds, normally it is used a gif image to make people understand that the pictures are loading.
About the option image lazy loading?

bye

**Comment by kthornbloom** [comment]
Yeah, that's a good idea. The only issue is the size is set by the images themselves, so I can't display the container until they have already loaded.

**Comment by kthornbloom** [comment]
Version 2 now supports this!
