### ISSUE TITLE
Touch devices

### ISSUE THREAD

**Issue by maofree** [kthornbloom/Smoothslides#6]
Hi kevin
this is not a bug, but just a suggestion
you can use this script with your plugin to add the support for touch devices
http://labs.rampinteractive.co.uk/touchSwipe
what do you think?

bye

**Comment by kthornbloom** [comment]
Hi sorry for the late reply. Getting caught up on this stuff now. While I like the idea of swipe functionality, I don't like requiring multiple dependancies for something as simple as a slideshow. We'll see though- it may be something I try to add in the future.
